### ISSUE TITLE
Auto unwrap for full reductions.

### ISSUE THREAD

**Issue by srush** [google-deepmind/penzai#8]
When you call full reductions like sum or any, you need to untag and then unwrap which is a bit painful. Seems safe to just auto unwrap there.

**Comment by srush** [comment]
Oh I realize I misunderstood the semantics. So .sum only reduces over the positional axes. And unwrap_all would be dangerous.

**Comment by danieldjohnson** [comment]
Yeah, that's right, *all* array methods on NamedArray instances (including reductions like `.sum()`) are vectorized using `nmap`, so they only see positional axes. This means something like `array.untag("foo", "bar").sum()` will sum only over the `"foo"` and `"bar"` axes, and it might still have named axes left over.

By the way, as a convenience, you can call `array.unwrap("foo", "bar")` instead of `array.untag("foo", "bar").unwrap()` if you want! The two are equivalent.

`unwrap_all` is a bit underspecified to have as part of the exposed API, since the order of the axes in the result is not guaranteed. Usually, I think idiomatic code should only operate on the axis names that it knows about explicitly. But if you *really* want to do a full reduction over every named axis, you can do something like `array.unwrap(*array.named_shape.keys())`.
