### ISSUE TITLE
Determinism in Gemma model

### ISSUE THREAD

**Issue by daralthus** [google-deepmind/penzai#82]
Hello!
I am trying to understand, is there a particular reason for this behaviour?
<img width="1118" alt="image" src="https://github.com/user-attachments/assets/fd6bf8ec-4e20-473b-8262-c4ebe517b712">

 From the code it seems like the model doesn't take an rng.
<img width="704" alt="image" src="https://github.com/user-attachments/assets/737f4434-62f8-441c-95dc-57f4eafb5077">

The model here is gemma, loaded as in the tutorial.

**Comment by danieldjohnson** [comment]
I believe this is a side effect of how JAX (and XLA) compute matrix-matrix products vs matrix-vector products. In short, batched matrix multiplication can cause XLA to use a different algorithm to compute the products, which can slightly change results due to the non-associativity of floating point operations.

Here's a related comment that seems to describe the same issue: https://github.com/google/jax/issues/20047#issuecomment-1975267301

Relevant bit:
> My gut feeling is that this is working as intended. Adding a batch dimension will allow and encourage XLA to change the order of operations, and floating point computations will not produce bitwise exact results if you change the order of operations. Indeed: that's sort of the point of vmap: we can and will compute things in a different and possibly more efficient order if there's a batch dimension.
>
> The most common place this surprises people is that adding a batch dimension to a matrix-vector multiplication makes it a matrix-matrix multiplication, which triggers different and sometimes lower precision matmul algorithms especially on GPUs and TPUs.

The size of the difference here is probably because you are using `bfloat16`, which is a very low precision format and can lead to cascading differences in model outputs. You could try initializing the model with `upcast_activations_to_float32=True`, which will use a higher precision to store the model activations and should lead to smaller discrepancies (at the cost of somewhat slower speed and higher memory usage).
